#!/usr/bin/env bash

re='^[0-9]+$'
mode="None"
invert="no"
# Gather all existing pane indexes into panel_array
IFS=": " read -r -a panel_array <<< $(tmux list-panes | awk '{print $1}' | tr ':\n' ' ')

Help()
{
   # Display Help
   echo "paneblock tmux help"
   echo
   echo "Syntax: paneblock [-h|d|e|i|a] <pane index(es)>"
   echo "options:"
   echo "h     Print this help."
   echo "d     disable input on <pane index>"
   echo "e     enable input on <pane index>"
   echo "i     invert selection (requires -e or -d flag)"
   echo "a     enable input on all panes"
   echo 
   echo "Examples:"
   echo "Disable input on panes 0,4,6:              \`paneblock -d 0 4 6\`"
   echo "Enable input on pane 4:                    \`paneblock -e 4\`"
   echo "Re-enable input on all panes:              \`paneblock -a\`"
   echo "Disable input on all panes EXCEPT 0,4,6:   \`paneblock -d -i 0 4 6\`"
   echo
}

for arg in "$@"; do
    case $arg in
        -h|--help)
            Help
            exit
            ;;
        -i|--invert)
            invert="yes"
            shift
            ;;
        -e|--enable)
            mode="-e"
            shift
            ;;
        -d|--disable)
            mode="-d"
            shift
            ;;
        -a|--all)
            mode="-a"
            shift
            ;;
    esac
done

# If invert: add all indexes that dont match the args input to the target_panes
if [ $invert = "yes" ];then
    target_panes=$(echo ${panel_array[@]} ${@} | tr ' ' '\n' | sort | uniq -u)
else
    # If 'all': Add all indexes to target_panes
    if [ $mode = "-a" ];then
        echo "Enabling input on all panes"
        target_panes=${panel_array[@]}
    # Add just the arg inputs to target_panes
    else
        target_panes=$@
    fi
fi

for pane in ${target_panes[@]};do
    # Check that remaining args are ints
    if ! [[ $pane =~ $re ]] ; then
        echo "Error: Args must be pane numbers" >&2; exit 
    fi
    # Ensure that a mode is set (e or d)
    if [ $mode = "None" ];then
        echo "Must set mode: -e or -d" >&2; exit 1
    fi
    # Run enable against target_panes
    if [[ $mode = "-e" || $mode = "-a" ]]; then
        echo "Enabling input on pane: $pane"
        tmux select-pane -t $pane -e
        # Update tmux pane title (if enabled in tmux.conf)
        tmux set-option -p -t $pane @custom_pane_title "enabled"
    fi
    # Run disable against target panes
    if [ $mode = "-d" ];then
        echo "Disabling input on pane: $pane"
        tmux select-pane -t $pane -d
        # Update tmux pane title (if enabled in tmux.conf)
        tmux set-option -p -t $pane @custom_pane_title "disabled"
    fi
done
